[package]
name = "goxlr-initialiser"
description = "Finds, checks and initialises any unconfigured GoXLR devices"
categories = ["hardware-support", "command-line-utilities"]

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Common Workspace
tokio = { workspace = true }
