[package]
name = "goxlr-audio"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Common Workspace
log = { workspace = true }
anyhow = { workspace = true }
fancy-regex = { workspace = true }  # Used for Finding Devices

# Symphonia for Audio Decoding.
symphonia = { version = "0.5.4", features = ["wav", "mp3", "ogg", "flac"] }

# Hound for WAV Encoding.
hound = "3.5.1"

# Audio Normalisation
ebur128 = "0.1.10"

# Ring Buffer
rb = "0.4.1"

# CPAL for Audio I/O
cpal = "0.16.0"
rubato = "0.16.1"
