[package]
name = "goxlr-daemon"
description = "Allows control of a TC-Helicon GoXLR or GoXLR Mini, by maintaining an interaction with it over USB in the background."
categories = ["hardware-support", "command-line-utilities"]

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
tts = ["dep:tts"]

[dependencies]
goxlr-usb = { path = "../usb" }
goxlr-ipc = { path = "../ipc" }
goxlr-types = { path = "../types" }
goxlr-audio = { path = "../audio" }
goxlr-profile-loader = { path = "../profile" }
goxlr-scribbles = { path = "../scribbles" }

# Common Workspace
log = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
json-patch = { workspace = true }
tokio = { workspace = true }
enumset = { workspace = true }
enum-map = { workspace = true }
interprocess = { workspace = true }
byteorder = { workspace = true }
clap = { workspace = true }
include_dir = { workspace = true }
cfg-if = { workspace = true }
lazy_static = { workspace = true }
fancy-regex = { workspace = true }
which = { workspace = true }

# Log File Handling
simplelog = "0.12.2"
file-rotate = "0.8.0"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }

# Project Directories
directories = "6.0.0"

# Linked Hashsets
ritelinked = "0.3.2"

# Opens a Browser or App
open = "5.3.2"

# Sampler Date Stamps
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }

# File Matching
glob = "0.3.3"

# Text to Speech
tts = { version = "0.26.3", features = ["tolk"], optional = true }

# File Change Notification
notify = "8.2.0"

# Language Guessing
sys-locale = "0.3.2"

## HTTPd Server
actix-web = { version = "4.11.0", default-features = false, features = ["macros", "compress-brotli", "compress-gzip"] }
actix-ws = "0.3.0"
actix-cors = "0.7.1"
actix-multipart = "0.7.2"

mime_guess = "2.0.5"
jsonpath-rust = "1.0.4"

# Used for Firmware Update Checks
reqwest = { workspace = true, features = ["stream", "rustls-tls"] }
xmltree = "0.11.0"
futures-util = "0.3.31"

# Windows Specific Dependencies
image = { workspace = true }
sysinfo = { workspace = true }
winrt-toast-reborn = "0.3.8"
mslnk = "0.1.8"
dunce = "1.0.5"
windows-args = "0.2.0"

winreg = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_LibraryLoader",
    "Win32_System_Shutdown",
    "Win32_System_RemoteDesktop"
] }

[build-dependencies]
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
directories = "6.0.0"
windres = { workspace = true }
