name: Create Release Build
on: [ workflow_dispatch, workflow_call ]
jobs:
  get_version:
    name: "Version"
    uses: ./.github/workflows/get-version.yml

  build_windows:
    name: "Create Windows Build"
    runs-on: windows-latest
    needs: [ get_version ]
    steps:
      - name: "Check out GoXLR Utility"
        uses: actions/checkout@v4

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Build GoXLR Release Installer"
        shell: pwsh
        run: |
          .\build-release.ps1

      - name: "Upload Installer Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: ./build-output/GoXLR.exe
